package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AsteroidField.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class AsteroidField {
	private Asteroid[] asteroids;
	public void MoveAsteroids() {
		TestLogger.EnterFunction("AsteroidField.MoveAsteroids");

		TestLogger.ExitFunction();
	}
	
	public void AddAsteroid(Asteroid asteroid) {
		TestLogger.EnterFunction("AsteroidField.AddAsteroid");
		TestLogger.ExitFunction();
	}
	
	public Asteroid[] GetAsteroids() {
		TestLogger.EnterFunction("AsteroidField.GetAsteroids");
		TestLogger.ExitFunction();
		return asteroids;
	}
	
	public void RemoveAsteroid(Asteroid asteroid) {
		TestLogger.EnterFunction("AsteroidField.RemoveAsteroid");
		TestLogger.ExitFunction();
	}
	
	public void HandleSolarStorm() {
		TestLogger.EnterFunction("AsteroidField.HandleSolarStorm");
		TestLogger.ExitFunction();
	}
}
