package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AsteroidField.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class AsteroidField {
	private Asteroid asteroids;
	public void MoveAsteroids() {
	}
	
	public void AddAsteroid(Asteroid asteroid) {
	}
	
	public Asteroid[] GetAsteroids() {
	}
	
	public void RemoveAsteroid(Asteroid asteroid) {
	}
	
	public void HandleSolarStorm() {
	}
}
