package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asteroid.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//


import java.util.Scanner;

public class Asteroid extends SpaceObject {
	private int layers;
	private float distanceFromSun;
	private Material core;
	private Asteroid neighbours;
	public void Drill() {
	}
	
	public Material Mine() {
	}
	
	public boolean PlaceMaterial(Material material) {
	}
	
	public void MoveAsteroid() {
	}
	
	public void Explode() {
	}

	public boolean CanHideIn() {
		Scanner sc = new Scanner(System.in);
		System.out.println("Can you hide in the asteroid? (y/n)");
		String answer = sc.nextLine();
		sc.close();
		if (answer.equals("y"))
			return true;

		return false;
	}
	
	public void AddWorker(Worker worker) {
	}
	
	public void RemoveWorker(Worker worker) {
	}
	
	public void SetCore(Material material) {
	}
	
	public void RemoveNeighbour(SpaceObject spaceObject) {
	}
	
	public void HandleSolarStorm() {
	}
	
	public boolean IsCloseToSun() {
	}
	
	public void RemoveNeighbour(SpaceObject spaceObject) {
	}
	
	public void AddWorker(Worker worker) {
	}
}
