package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Game {
	private Astronaut players;
	private Worker workers;
	private AsteroidField asteroidField;
	private SolarStorm solarStorm;
	private BillOfMaterials billOfMaterials;
	public void DoRound() {
	}
	
	public void CheckWinOrLose() {
	}
	
	public void HandleSolarStorm() {
	}
	
	public void AddWorker(Worker worker) {
	}
	
	public void RemoveWorker(Worker worker) {
	}
	
	public void StartGame() {
	}
}
