package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nothing.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Nothing extends Material implements Material {
	public boolean CanHideIn() {
	}
}
