package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RadioactiveMaterial.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public abstract class RadioactiveMaterial extends Material implements Material {
	public void HandleCloseToSun(Asteroid asteroid) {
	}
}
