package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Robot extends Worker implements Worker {
	private BillOfMaterials billOfMaterials;
	public void Step() {
	}
	
	public void Explode() {
	}
	
	public void Move() {
	}
	
	public void Step() {
	}
	
	public void Move() {
	}
}
