package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SpaceObject.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public abstract class SpaceObject {
	private Worker workers;
	public void AddNeighbour(SpaceObject spaceObject) {
	}
	
	public SpaceObject[] GetNeighbours() {
	}
	
	public abstract void RemoveNeighbour(SpaceObject spaceObject);
	
	public abstract void AddWorker(Worker worker);
}
