package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teleporter.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Teleporter extends SpaceObject {
	private boolean active;
	private Teleporter pair;
	private Asteroid parent;
	private Teleporter pair;
	private BillOfMaterials billOfMaterials;
	public void LinkTo(Teleporter teleporter) {
	}
	
	public void Place(Asteroid asteroid) {
	}
	
	public void PairPlaced() {
	}
	
	public Asteroid GetParent() {
	}
	
	public void RemoveNeighbour(SpaceObject spaceObject) {
	}
	
	public void TeleportWorker(Worker worker) {
	}


	public void AddWorker(Worker worker) {
	}
	
	public static Teleporter[] CreateTeleporterPair(Material[] materials) {
	}
	
	public void RemoveNeighbour(SpaceObject spaceObject) {
	}
	
	public void AddWorker(Worker worker) {
	}
}
