package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeleporterPair.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class TeleporterPair {
	private Asteroid firstLocation;
	private Asteroid firstLocation;
	public boolean Place(Asteroid asteroid) {
	}
}
