package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uranium.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Uranium extends RadioactiveMaterial, Material implements RadioactiveMaterial {
	public void HandleCloseToSun(Asteroid asteroid) {
	}
}
