package game_classes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Worker.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public abstract class Worker {
	protected SpaceObject position;
	public void TravelTo(SpaceObject spaceObject) {
	}
	
	public void Drill() {
	}
	
	public void Wait() {
	}
	
	public void Explode() {
	}
	
	public void HandleSolarStorm() {
	}
	
	public void Die() {
	}
	
	public abstract void Step();
	
	public abstract void Move();
}
