//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Astronaut.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Astronaut extends Worker implements Worker {
	private TeleporterPair teleporters;
	private Material materialsStored;
	private Teleporter teleporters;
	public void Mine() {
	}
	
	public void PlaceMaterial(Material material) {
	}
	
	public void PlaceTeleporter() {
	}
	
	public void CreateRobot() {
	}
	
	public void CreateTeleporter() {
	}
	
	public void Step() {
	}
	
	public void Explode() {
	}
	
	public Material[] GetStoredMaterials() {
	}
	
	public void Move() {
	}
	
	public void Step() {
	}
	
	public void Move() {
	}
}
