//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BillOfMaterials.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class BillOfMaterials {
	public bool IsEnough(Material[] materials) {
	}
}
