//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Coal.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Coal extends Material implements Material {
}
