//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Ice extends VanishingMaterial, Material implements Material {
	public void HandleCloseToSun(Asteroid asteroid) {
	}
}
