//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Material.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public abstract class Material {
	public void HandleCloseToSun(Asteroid asteroid) {
	}
}
