//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SolarStorm.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class SolarStorm {
	private int timeTillHit;
	public bool Tick() {
	}
}
